# Generated by Django 5.1.2 on 2024-10-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='description',
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
